### ISSUE TITLE
Youtube video player should not suggest more videos 

### ISSUE THREAD

**Issue by Devendrakhatrii** [isarojdahal/learn.everydaykarmaa.com#15]
while learning about a topic the player should not suggest other video which are irrevelent to topic and are from other channels
- It will more likely prevent user form leaving the platform 
- avoid distraction while learning 
- if it suggests then it should suggest this channel videos

https://github.com/user-attachments/assets/62a54d16-80db-4613-bbd1-939473e039ce

**Comment by isarojdahal** [comment]
This issue has been resolved.
Thanks for the issue.
