### ISSUE TITLE
To add Podomoro Timer 

### ISSUE THREAD

**Issue by isarojdahal** [isarojdahal/learn.everydaykarmaa.com#8]
Concept : 
It can be placed on Navbar, called 'Start Learning' and when user taps on it,  a dialog box will appear asking for preferred amount of leraning time; and once set, the timer starts in place of 'Start Learning' .
Once the timer reaches to 0:00 a confetti is displayed on center of screen.

Note: Its data will be persistent and will be visible across the pages.

**Comment by theanupambista** [comment]
working on it
